
spring:
  cloud:
    stream:
      function:
        definition: customerProducer;customerConsumer;userProducer;userConsumer
      kinesis:
        binder:
          kpl-kcl-enabled: false
        bindings:
          customerConsumer-in-0:
            consumer:
              shardIteratorType: TRIM_HORIZON
          userConsumer-in-0:
            consumer:
              shardIteratorType: TRIM_HORIZON
      bindings:
        customerProducer-out-0:
          producer:
            useNativeEncoding: false
          destination: test_stream_jc_glue_json
          content-type: application/json
#          content-type: application/*+avro
        customerConsumer-in-0:
          consumer:
            useNativeDecoding: false
          destination: test_stream_jc_glue_json
          content-type: application/json
#          content-type: application/*+avro
        userProducer-out-0:
          destination: test_stream_jc_user
          content-type: application/*+avro
        userConsumer-in-0:
          destination: test_stream_jc_user
          content-type: application/*+avro

management:
  endpoints:
    web:
      exposure:
        include: "*"

#logging:
#  level:
#    com:
#      amazonaws:
#        services:
#          schemaregistry: debug
#    org:
#      apache:
#        http: info
#      springframework:
#        cloud:
#          stream: debug
#        integration: debug

cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
